version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: my_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
#      db:
#        condition: service_healthy
    networks:
      - my_network

  db:
    image: postgres:13
    container_name: my_postgres_db
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
